[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    electroniccats/MPU6050 @ ^0.6.0
    mikalhart/TinyGPSPlus @ ^1.0.3
