<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roadeye_perception</name>
  <version>1.0.0</version>
  <description>C++ ONNX Runtime perception engine for object, pothole, road segmentation, and depth estimation.</description>
  <maintainer email="dev@roadeye.ai">RoadEye Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>

  <depend>roadeye_dashboard_msgs</depend>
  <depend>roadeye_utils</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
